#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDdhc4tvGjD9GELggv6eFfT4HL0wpVEg4G0CtVatiWVALMI/Zg62Ne7sJuQWTwGP+npdkfh/0zBdlQpfWc8FG+Wwg+jbRk1MqGNZD7WlwG+jFVu/UKqJ5svLZdnndxZ6b89Q9q1Szt1VWY0jFaaf74Q68/1OidOkEuw9W+TQZHZWAt6UyU3/7K0ZuNfeGEHfuf5kqM9gAkHC8FO7U2ZzyGo+uWsOcIC1oFjpihU07WZZciOkDGES45CYjPosCSCPeSacenFD9rkrZg4+ub/sVUS9pFqcMaBn0i7fc0/6JkbRXNeCx/8lFpVt2ZDgoI3X9s0Z4AqJHDE9NBxndqo80Sx root@debian

write_files:
  - path: /var/lib/rancher/conf/cloud-config.yml
    permissions: "0644"
    owner: root
    content: |
      #cloud-config
      ssh_authorized_keys:
	- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDdhc4tvGjD9GELggv6eFfT4HL0wpVEg4G0CtVatiWVALMI/Zg62Ne7sJuQWTwGP+npdkfh/0zBdlQpfWc8FG+Wwg+jbRk1MqGNZD7WlwG+jFVu/UKqJ5svLZdnndxZ6b89Q9q1Szt1VWY0jFaaf74Q68/1OidOkEuw9W+TQZHZWAt6UyU3/7K0ZuNfeGEHfuf5kqM9gAkHC8FO7U2ZzyGo+uWsOcIC1oFjpihU07WZZciOkDGES45CYjPosCSCPeSacenFD9rkrZg4+ub/sVUS9pFqcMaBn0i7fc0/6JkbRXNeCx/8lFpVt2ZDgoI3X9s0Z4AqJHDE9NBxndqo80Sx root@debian
      rancher:
        state:
          dev: LABEL=RANCHER_STATE
        services_include:
          ubuntu-console: true
        network:
          dns:
            override: true
            nameservers:
              - 192.168.30.11
              - 192.168.30.12
          interfaces:
            eth0:
              dhcp: true
            eth1:
              dhcp: false
hostname: rancher-tayirvadai
rancher:
  state:
    dev: LABEL=RANCHER_STATE
  services_include:
    ubuntu-console: true
  console: ubuntu
  network:
    dns:
      override: true
      nameservers:
        - 192.168.30.11
        - 192.168.30.12
    interfaces:
      eth0:
        dhcp: true
      eth1:
        dhcp: false
